language: python
python:
  - "3.5"
install:
  - pip install pandas
  - pip install gmplot
  - pip install matplotlib
  - pip install numpy
  
script:
  - main.py
  
branches:
  only:
   - master
   
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
