language: python
python:
  - "3.7"
install:
  - pip install pandas
  - pip install gmplot
  - pip install matplotlib
  - pip install numpy
  
script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pwd
  - python Run_Pipline.py
  - echo "Done Done"
branches:
  only:
   - master
   
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

after_deploy:
  - git add Testing
  - git commit -m "Updating Execution"
  - git push
 
notifications:
  email:
    recipients:
   #   - prithvisekhp@xxx.com #default sends to registered email
    on_success: always
    on_failure: always
